source 'https://rubygems.org'

gem 'thin',         '= 1.6.1'
gem 'sinatra',      '= 1.3.6'
gem 'data_mapper',  '= 1.2.0'
gem 'sinatra-flash', '= 0.3.0'
gem 'sinatra-contrib', '= 1.3.2'
gem 'haml',         '= 4.0.4'
gem 'bcrypt-ruby',  '= 3.1.2'
gem 'json',  		'= 1.8.1'
gem 'mail',  		'= 2.5.4'
gem 'sinatra-paginate', '=0.1.0'
gem 'whenever',		'= 0.8.4'
gem 'rmagick',      '= 6.1.2'
gem 'rake', 		'= 10.1.0'
gem 'rack',			'= 1.5.2'
gem 'dm-sqlite-adapter',  '= 1.2.0'
gem 'net-smtp', require: false
